const players = [
  {
    firstName: 'Jalen',
    lastName: 'Brunson',
    position: 'PG',
    age: 28,
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3934672.png&w=350&h=254',
    detail: 'Son of former NBA player Rick Brunson and known for his clutch plays in the playoffs.',
  },
  {
    firstName: 'Mikal',
    lastName: 'Bridges',
    position: 'SF',
    age: 28,
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3147657.png',
    detail: 'Famous for his defensive skills and once played every minute of a playoff game.',
  },
  {
    firstName: 'Karl-Anthony',
    lastName: 'Towns',
    position: 'C',
    age: 29,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1626157.png',
    detail: 'Known for his three-point shooting ability as a center, a rare skill at his position.',
  },
  {
    firstName: 'Mitchell',
    lastName: 'Robinson',
    position: 'C',
    age: 26,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1629011.png',
    detail: 'Has a background in track and field, which contributes to his incredible athleticism.',
  },
  {
    firstName: 'OG',
    lastName: 'Anunoby',
    position: 'SF',
    age: 27,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1628384.png',
    detail: 'Known for his lockdown defense and improving three-point shooting every season.',
  },
  {
    firstName: 'Miles',
    lastName: 'McBride',
    position: 'PG',
    age: 24,
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431823.png',
    detail: 'Recognized for his high basketball IQ and gritty defensive style.',
  },
  {
    firstName: 'Josh',
    lastName: 'Hart',
    position: 'SG',
    age: 29,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1628404.png',
    detail: 'Has a reputation for his hustle and energy off the bench.',
  },
  {
    firstName: 'Anton',
    lastName: 'Watson',
    position: 'PF',
    age: 24,
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431705.png&w=350&h=254',
    detail: 'Known for his versatility and ability to guard multiple positions.',
  },
  {
    firstName: 'Precious',
    lastName: 'Achiuwa',
    position: 'PF',
    age: 25,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1630173.png',
    detail: 'Started his college career as a guard before transitioning to forward/center.',
  },
  {
    firstName: 'Cameron',
    lastName: 'Payne',
    position: 'PG',
    age: 30,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1626166.png',
    detail: 'Known for his speed and playmaking off the bench.',
  },
  {
    firstName: 'Landry',
    lastName: 'Shamet',
    position: 'SG',
    age: 27,
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3914044.png',
    detail: 'Noted for his shooting accuracy, especially from three-point range.',
  },
  {
    firstName: 'Tyler',
    lastName: 'Kolek',
    position: 'PG',
    age: 23,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1642278.png',
    detail: 'Highly regarded for his passing ability and court vision.',
  },
  {
    firstName: 'Delon',
    lastName: 'Wright',
    position: 'SG',
    age: 32,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1626153.png',
    detail: 'Known for his defense and versatility to play multiple guard positions.',
  },
  {
    firstName: 'Ariel',
    lastName: 'Hukporti',
    position: 'C',
    age: 22,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1630574.png',
    detail: 'One of the youngest players, coming from a strong international basketball background.',
  },
  {
    firstName: 'Jericho',
    lastName: 'Sims',
    position: 'C',
    age: 26,
    photo: 'https://media.bleacherreport.com/image/upload/x_0,y_101,w_1799,h_1198,c_crop/w_800,h_533,c_fill/v1736814808/rc9zblyvsea5ju1mzfww.jpg',
    detail: 'Known for his physical play and rebounding skills.',
  },
  {
    firstName: 'Pacome',
    lastName: 'Dadiet',
    position: 'PG',
    age: 19,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1642359.png',
    detail: 'One of the youngest players in the league, known for his quickness.',
  },
  {
    firstName: 'Matt',
    lastName: 'Ryan',
    position: 'SF',
    age: 27,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1630346.png',
    detail: 'Has a strong shooting touch and ability to stretch the floor.',
  },
  {
    firstName: 'Jacob',
    lastName: 'Toppin',
    position: 'SF',
    age: 24,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1631210.png',
    detail: 'Known for his athleticism and energy on defense.',
  },
  {
    firstName: 'Kevin',
    lastName: 'McCullar Jr.',
    position: 'SF',
    age: 23,
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4411057.png&w=350&h=254',
    detail: 'Has a reputation for being a tough defender and good rebounder.',
  },
  {
    firstName: 'MarJon',
    lastName: 'Beauchamp',
    position: 'SF',
    age: 24,
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432179.png&w=350&h=254',
    detail: 'Known for his versatility and improving offensive skills.',
  },
];
