const players = [
  {
    firstName: 'Jalen',
    lastName: 'Brunson',
    position: 'PG',
    age: 28,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Mikal',
    lastName: 'Bridges',
    position: 'SF',
    age: 28,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Karl-Anthony',
    lastName: 'Towns',
    position: 'C',
    age: 29,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Mitchell',
    lastName: 'Robinson',
    position: 'C',
    age: 26,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'OG',
    lastName: 'Anunoby',
    position: 'SF',
    age: 27,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Miles',
    lastName: 'McBride',
    position: 'PG',
    age: 24,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Josh',
    lastName: 'Hart',
    position: 'SG',
    age: 29,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Anton',
    lastName: 'Watson',
    position: 'PF',
    age: 24,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Precious',
    lastName: 'Achiuwa',
    position: 'PF',
    age: 25,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Cameron',
    lastName: 'Payne',
    position: 'PG',
    age: 30,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Landry',
    lastName: 'Shamet',
    position: 'SG',
    age: 27,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Tyler',
    lastName: 'Kolek',
    position: 'PG',
    age: 23,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Delon',
    lastName: 'Wright',
    position: 'SG',
    age: 32,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Ariel',
    lastName: 'Hukporti',
    position: 'C',
    age: 22,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Jericho',
    lastName: 'Sims',
    position: 'C',
    age: 26,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Pacome',
    lastName: 'Dadiet',
    position: 'PG',
    age: 19,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Matt',
    lastName: 'Ryan',
    position: 'SF',
    age: 27,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Jacob',
    lastName: 'Toppin',
    position: 'SF',
    age: 24,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'Kevin',
    lastName: 'McCullar Jr.',
    position: 'SF',
    age: 23,
    photo: 'https://picsum.photos/200',
  },
  {
    firstName: 'MarJon',
    lastName: 'Beauchamp',
    position: 'SF',
    age: 24,
    photo: 'https://picsum.photos/200',
  },
];
