const players = [
  {
    firstName: 'Jalen',
    lastName: 'Brunson',
    position: 'PG',
    age: 28,
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3934672.png&w=350&h=254',
  },
  {
    firstName: 'Mikal',
    lastName: 'Bridges',
    position: 'SF',
    age: 28,
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3147657.png',
  },
  {
    firstName: 'Karl-Anthony',
    lastName: 'Towns',
    position: 'C',
    age: 29,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1626157.png',
  },
  {
    firstName: 'Mitchell',
    lastName: 'Robinson',
    position: 'C',
    age: 26,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1629011.png',
  },
  {
    firstName: 'OG',
    lastName: 'Anunoby',
    position: 'SF',
    age: 27,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1628384.png',
  },
  {
    firstName: 'Miles',
    lastName: 'McBride',
    position: 'PG',
    age: 24,
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431823.png',
  },
  {
    firstName: 'Josh',
    lastName: 'Hart',
    position: 'SG',
    age: 29,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1628404.png',
  },
  {
    firstName: 'Anton',
    lastName: 'Watson',
    position: 'PF',
    age: 24,
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431705.png&w=350&h=254',
  },
  {
    firstName: 'Precious',
    lastName: 'Achiuwa',
    position: 'PF',
    age: 25,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1630173.png',
  },
  {
    firstName: 'Cameron',
    lastName: 'Payne',
    position: 'PG',
    age: 30,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1626166.png',
  },
  {
    firstName: 'Landry',
    lastName: 'Shamet',
    position: 'SG',
    age: 27,
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3914044.png',
  },
  {
    firstName: 'Tyler',
    lastName: 'Kolek',
    position: 'PG',
    age: 23,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1642278.png',
  },
  {
    firstName: 'Delon',
    lastName: 'Wright',
    position: 'SG',
    age: 32,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1626153.png',
  },
  {
    firstName: 'Ariel',
    lastName: 'Hukporti',
    position: 'C',
    age: 22,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1630574.png',
  },
  {
    firstName: 'Jericho',
    lastName: 'Sims',
    position: 'C',
    age: 26,
    photo: 'https://media.bleacherreport.com/image/upload/x_0,y_101,w_1799,h_1198,c_crop/w_800,h_533,c_fill/v1736814808/rc9zblyvsea5ju1mzfww.jpg',
  },
  {
    firstName: 'Pacome',
    lastName: 'Dadiet',
    position: 'PG',
    age: 19,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1642359.png',
  },
  {
    firstName: 'Matt',
    lastName: 'Ryan',
    position: 'SF',
    age: 27,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1630346.png',
  },
  {
    firstName: 'Jacob',
    lastName: 'Toppin',
    position: 'SF',
    age: 24,
    photo: 'https://cdn.nba.com/headshots/nba/latest/1040x760/1631210.png',
  },
  {
    firstName: 'Kevin',
    lastName: 'McCullar Jr.',
    position: 'SF',
    age: 23,
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4411057.png&w=350&h=254',
  },
  {
    firstName: 'MarJon',
    lastName: 'Beauchamp',
    position: 'SF',
    age: 24,
    photo: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432179.png&w=350&h=254',
  },
];
